version: "3"

x-logging: &fluent-bit
    driver: fluentd
    options:
        fluentd-address:  172.21.0.2:24224

services:
  review-database:
    image: mongo
    restart: always
    networks:
      - servers
      - monitoring
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    volumes:
      - './database-data:/data/db'
    logging: *fluent-bit
    

  review-service:
    build: .
    restart: on-failure
    networks:
      - servers
      - monitoring
    container_name: review-service
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      SERVICE_PATH:  0.0.0.0:8082
      JAEGER_SERVICE_NAME: review-service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - "8082:8082"
    logging: *fluent-bit
    depends_on:
      review-database:
        condition: service_healthy

volumes:
  review-data:

networks:
  servers:
    external: true
  monitoring:
    external: true
