name: PR workflow

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Build
              run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build

        services:
            mongodb:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: user
                    MONGO_INITDB_ROOT_PASSWORD: pass
                ports:
                    - 27017:27017

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Test
              env:
                  DATABASE_CONNECTION_STRING: mongodb://user:pass@localhost:27017
                  SERVICE_PATH: 0.0.0.0:8083
              run: go test -v ./...
