name: Push workflow

permissions: write-all
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Build
              run: go build -v ./...

    test:
        runs-on: ubuntu-latest
        needs: build

        services:
            mongodb:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: user
                    MONGO_INITDB_ROOT_PASSWORD: pass
                ports:
                    - 27017:27017

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.19"

            - name: Test
              env:
                  DATABASE_CONNECTION_STRING: mongodb://user:pass@localhost:27017
                  SERVICE_PATH: 0.0.0.0:8083
              run: go test -v ./...
    analyze:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
            - uses: actions/checkout@v3

            # Initializes the CodeQL tools for scanning.
            # https://github.com/github/codeql-action
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: go

            # Autobuild attempts to build any compiled languages
            - name: Autobuild
              uses: github/codeql-action/autobuild@v2

            # Perform GitHub Code Scanning.
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2
    release:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Git tag echo
              run: git tag

            - name: Release
              id: semantic
              uses: codfish/semantic-release-action@v2.0.0
              with:
                  branches: |
                      [
                       'master'
                      ]
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              env:
                  OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
              with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/windbnb-review-service:${{ steps.semantic.outputs.release-version }},${{ secrets.DOCKERHUB_USERNAME }}/windbnb-review-service:latest
                  cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/windbnb-review-service:latest
